language: android
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-19.1.0
    - android-19
    - sysimg-19
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'
before_script:
  - echo no | android create avd --force -n test -d 3 -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - chmod a+x ./wait_for_emulator.sh
  - chmod a+x ./gradlew
  - ./wait_for_emulator.sh
  - sleep 10
  - adb shell input keyevent 82
  - adb shell input keyevent 4
  - sleep 10
script:
  - ./gradlew connectedAndroidTest
after_success:
  - gradle coveralls